name: Testing Workflow

on: push 

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7.x', '3.8.x']

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install Dependencies
      run: pip install -r requirements/dev.txt

    - name: Run Linting and Tests
      env:
        ALLOWED_HOSTS: "*"
        DATABASE_URL: sqlite://
        SECRET_KEY: secret
      run: cd src && scripts/test

    - name: Upload Coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./src/coverage.xml
